### ISSUE TITLE
Add "Register" button

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#104]
Some events require registration. Can we:
- Add a registration column in the sheet
- If the column is populated with a '1', have the call-to-action button say 'Register'

**Comment by mstem** [comment]
Icon attached 
![noun_Ticket_3386667](https://user-images.githubusercontent.com/613432/84419659-36192980-ac19-11ea-8102-02489a2eb8b8.png)

https://www.dropbox.com/s/r7t4oxq02vzhjnw/noun_Ticket_3386667.svg?dl=0

**Comment by jjandoc** [comment]
So should I assume with this icon that we're also adding a badge to the event description? This isn't just a CTA copy change?

**Comment by mstem** [comment]
Yes, please add the badge to the event description as well
