### ISSUE TITLE
Load videos within the Guide where possible

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#11]
For platforms that allow it, load the video in the Guide itself without the user having to leave. This could be a frame, popover, etc.

Update: I did some initial looking and many of the top platforms allow embedding (if the producer does), so it may be possible for us to do this systematically given the user ID: https://docs.google.com/spreadsheets/d/1D5JBmEg1teTHy43Gu0lJqlTJCp_T3lmHljAO5l_tEwk/edit#gid=1656008924

Please LMK what we'd need to collect on the data entry side for each platform -- embed code? User ID? Just the livestream URL?

The order of priority for video platforms based on our data collected is:

YouTube
Facebook Live
Livestream (Vimeo)
Twitch
Instagram

(To the extent each is even possible)

When a video is being played, we'd need to prevent scrolling listing entries from taking over the preview pane as they are currently set to do.

**Comment by jjandoc** [comment]
I think the easiest thing here is to add a column for "embedUrl". Assuming most platforms support embedding via an iframe, then we just need the URL src for that iframe and we can display that directly. As a backup, if the platform is fairly normalized then we can probably parse out what the video embed code should be. For instance, given the URL: https://www.youtube.com/watch?time_continue=60&v=eyBP2SlwW8U, I can figure out that the platform is YouTube, and I know that YouTube's embed URL for that would be https://www.youtube.com/embed/eyBP2SlwW8U.

I already have this in place and live for YouTube. Let me take a look at the other platforms.

**Comment by jjandoc** [comment]
Based off of what's in the spreadsheet right now, I can't parse out Facebook Live videos since the links are to the channel/user, not the livestream themselves. Same with Twitch and Instagram. I did manage to get Livestream parsed.

**Comment by mstem** [comment]
Good point... none of these make it easy to get the URL until after it's
live. Youtube and Livestream will be a good start.

**Comment by mstem** [comment]
A Livestream example:
`<iframe title="vimeo-player" src="https://player.vimeo.com/video/416185214" width="640" height="360" frameborder="0" allowfullscreen></iframe>`

More configurations are available at Vimeo.com: https://vimeo.com/416185214#embed

Another Livestream example:

`<iframe id="ls_embed_1589064542" src="https://livestream.com/accounts/684952/events/9118699/player?width=640&height=360&enableInfoAndActivity=true&defaultDrawer=&autoPlay=true&mute=true" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen> </iframe>`

More configurations available on Livestream.com: https://livestream.com/tucsonunifiedlive/events/9118699?customizeShare=true

**Comment by mstem** [comment]
Stitcher, for podcasts, is very consistent: 

`<iframe style="border: solid 1px #dedede;"  src="https://app.stitcher.com/splayer/f/159738/69466314" width="220" height="150" frameborder="0" scrolling="no"></iframe>`
