### ISSUE TITLE
Re-design mobile experience

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#123]
We've been asked to add the media player to the mobile (smaller screens) view. Let's use the opportunity to reimagine the mobile experience.

See mockups for a layout change that stacks channels and listings vertically on mobile, rather than in a grid, to better fit the mobile form factor.

Changes required:
- strike identity banner at the top (maybe we move it to the very bottom of the vertical list?)
- add the media pane
- when user taps 'Watch' button on an entry, play it in the media pane
- strike the blue time bar
- display Channel names stacked vertically over listings
- display only the current half-hour timeslot
- display only Channels with an entry in the current timeslot (something is scheduled in the channel when the user is looking)

![liveguide mobile stacked channels](https://user-images.githubusercontent.com/613432/85202948-74de6c00-b30a-11ea-87ff-4ff779e69708.png)

![liveguide mobile expanded](https://user-images.githubusercontent.com/613432/85202944-714ae500-b30a-11ea-8c85-c1c83f797a24.png)

**Comment by jjandoc** [comment]
I like this! What should display if there are no active events - like in the middle of the night?

**Comment by mstem** [comment]
Great question and related to the general idea for an overnight
placeholder. Perhaps Margo can design us something about "We'll be back in
the morning, Boston-time"?
