### ISSUE TITLE
Design: Revisit color palette with official colors

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#20]
https://company-59374.frontify.com/d/ERwMkYdG4A1L/the-boston-globe#/visual-identity-guidelines/color-palette

**Comment by margoyle** [comment]
yellow: #FFD44D
navy: #08285A (these should both be the same as before)
gray: #E1E3E6
dark red: #9B1519
royal blue: #005DC7
dark gray: #4A4A4A (for tag icons)
