### ISSUE TITLE
Add icon for donation pages

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#30]
Many of the livestreams are charity fundraisers. We can collect the donation page URL while collecting data. Could we add a donate icon to entries where this field is populated?

**Comment by jjandoc** [comment]
A "Donate" link will appear in the event description if a donation url exists. Is there anything else we want to do here?

**Comment by mstem** [comment]
Could it be a donate button? In the same style as the watch button?

**Comment by jjandoc** [comment]
Yeah, it's already a button.

<img width="569" alt="Screen Shot 2020-05-09 at 12 44 56 PM" src="https://user-images.githubusercontent.com/801206/81483429-e945cb80-91f2-11ea-9dcc-725f65325a16.png">
