### ISSUE TITLE
Update lower right action buttons with the attached

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#33]
Jon helpfully added a donate button for the Boston's Still Running campaign in the lower right of the app. To avoid confusion with paid channels (Netflix, Hulu, etc.), could you think about another glpyh we might use on that button?
![buttons](https://user-images.githubusercontent.com/613432/81485642-f1335900-924e-11ea-8462-2784e16747bb.png)

**Comment by margoyle** [comment]
[grid buttons.zip](https://github.com/exafox/paquete/files/4606104/grid.buttons.zip)
weird that github won't let me upload svgs tbh
