### ISSUE TITLE
Design: Tags for listing descriptors

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#34]
These aren't all immediately necessary, but we might as well execute them in one pass. (The answer may be "use an icon pack"). 

We'd like flags that communicate if an entry is:
- Audio (for podcasts - headphones icon?)
- Adult content
- Costs money ($) - Netflix, Hulu, some charity livestreams
- Donation (many of the livestreams are donation-based and we can collect the donation link, so some sort of give / donate icon?)
- Sponsored (hypothetically)

**Comment by margoyle** [comment]
@mstem I assume we can purchase some icons? I'm using 3 from noun project
https://thenounproject.com/term/heart/3329877/
https://thenounproject.com/term/headphones/1219649/
https://thenounproject.com/term/donation/3327633/

**Comment by margoyle** [comment]
They're $2.99 each so cheap

**Comment by margoyle** [comment]
[tag icons.zip](https://github.com/exafox/paquete/files/4606099/tag.icons.zip)

**Comment by mstem** [comment]
Nice!

**Comment by margoyle** [comment]
@mstem answer to your question about purchasing icons in this thread! going to come to about $8.97 and we won't have to credit noun project.

**Comment by mstem** [comment]
perf
