### ISSUE TITLE
Resolve stacking/overlap issue

### ISSUE THREAD

**Issue by margoyle** [exafox/paquete#36]
<img width="1106" alt="Screen Shot 2020-05-10 at 2 24 23 PM" src="https://user-images.githubusercontent.com/6528572/81507294-609a5e80-92ca-11ea-927c-63ebda3d473e.png">

**Comment by margoyle** [comment]
<img width="756" alt="Screen Shot 2020-05-10 at 2 29 50 PM" src="https://user-images.githubusercontent.com/6528572/81507346-c1c23200-92ca-11ea-9703-95d2c8adc880.png">
proposed design, possibly for later implementation?

**Comment by mstem** [comment]
The proposed design is nice. As an immediate solution, I will try to have Google Sheets flag overlap conflicts with conditional formatting.
