### ISSUE TITLE
Icon tags as listing descriptors

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#39]
We'd like the ability to display flags to the right of the listing title that communicate if an entry is audio, adult, paywalled, charity, or sponsored.

Ideally we could toggle these tags' appearance with a 1 or 0 in a new column in the Streaming Guide Sheet. If we can do that, please append them to the right of the existing columns, as our data ingesters are now based on the existing column order.

Icons: Margo's made these: https://github.com/exafox/paquete/files/4606099/tag.icons.zip

Alt text for the images:

- Audio content (a podcast) (Alt text: Audio content)
- Adult content (Alt text: May contain adult content)
- Paywalled (some charity livestreams, and Netflix, Hulu entries) (Alt text: May require paid ticket or subscription)
- Donation page available (link this icon to ) (Alt text: This event is for charity. Please consider giving.)
- Sponsored (hypothetically) (Alt text: This listing is sponsored)

**Comment by mstem** [comment]
If the icons don't fit well in the grid itself, we can display them in just the expanded preview panel 
![listing icons](https://user-images.githubusercontent.com/613432/81509390-995a2800-930a-11ea-9f0f-94317c236064.png)

**Comment by jjandoc** [comment]
This is in place for the preview panel. Let me know where we land for changes to the grid. I spoke with @margoyle and she mentioned we're possibly going to remove everything except the event title and the icons.
