### ISSUE TITLE
Add a thin brand header bar

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#43]
We have a request for minimal yet persistent branding in the form of a thin bar across the top of the app that reads "Presented by [The Boston Globe logo], and an about link [encircled 'i' information icon?] that pops up a modal with some explainer text.

**Comment by margoyle** [comment]
![branding1](https://user-images.githubusercontent.com/6528572/82127105-32f85e00-977f-11ea-893b-e82cd0924c30.png)
![branding2](https://user-images.githubusercontent.com/6528572/82127106-32f85e00-977f-11ea-8539-a62888105268.png)
Two options here, one very small and one a little bigger. If The boston.com header is going to be at the top of the page I prefer the smaller one, but if not then let's go with the larger.

**Comment by margoyle** [comment]
![layout_desktop copy 34](https://user-images.githubusercontent.com/6528572/82127229-ea8d7000-977f-11ea-9cae-2887d0557512.png)
And another two options for the popup - a modal or a tooltip. I prefer the tooltip.

**Comment by mstem** [comment]
Really nice! It will indeed be just this header, so I agree the second one looks nicer. 

I think you may have only uploaded one of the two, unless I'm missing it?

**Comment by jjandoc** [comment]
Is this only for Boston Globe version, or for both versions?

Do we know when we'll have copy?

**Comment by mstem** [comment]
I'll work on getting the copy now

**Comment by jjandoc** [comment]
Added this, though still waiting on copy. I implemented as a modal initially because it's much easier to do, but I can circle back and do this as a tooltip if people feel strongly about doing it that way instead.

**Comment by mstem** [comment]
We have copy:

The Boston Globe is proud to present LiveGuide, your daily schedule of the latest livestreams and other content from around the internet. Stay tuned for entertainment, news, virtual events, and the Globe's critics' picks.  Do you have a livestream you’d like us to consider including in LiveGuide?  Provide us with the details [here](https://docs.google.com/forms/d/e/1FAIpQLSe3aSBtDI7rgL5vhsvqqjD9UoLa6BHuL0Xa3wyS1T-kazvl6w/viewform?usp=send_form).
