### ISSUE TITLE
Ad unit

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#48]
Can we replace the placeholder image (network color bars) with an ad unit? See the square ad above the "Visual stories" section at https://www.bostonglobe.com/

width:300px;height:250px;

**Comment by mstem** [comment]
In the Boston.com version only, we'd like to add two ad units (through Google Publisher Tags).

1. a 300x250 (square-ish) unit to display instead of the network color bars when there's no media in the media pane
2. a 320x50 unit, to display in the schedule grid itself. I could pass it through via the Google Sheet, if setting a specific date/time is important.

Are both or either of these possible to implement?

**Comment by jjandoc** [comment]
Hmm, so a few thoughts here.

 The main thing is that the dimensions on this page are fairly fluid at the moment. The top-right square is essentially just 50% height and 50% width. This may or may not fit an ad - depends on the user's screen. The layout changes from mobile to desktop at 768px, so the width will at least work - the square will always be at the very minimum 384px. No assurances on the height, though.  We can set a minimum height on the block if necessary, but I would need to do some style refactoring. Or we can just say if the user happens to have a very short window (less than about 500px) then they don't see all of the ad.

For the ad that would be dropped in the schedule grid - I think maybe I can just make a dedicated row for the ad so it doesn't possibly conflict with actual content. Maybe that involves creating a "channel" called "Advertising" - or maybe I can just style it as a full bar. I'll play around with it a little to see.

Are there code snippets I need to drop in for these?

**Comment by mstem** [comment]
Holding off while we clarify
