### ISSUE TITLE
Is Demo still working?

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#50]
I'm having issues with the Demo Paquete app.

It was freezing a lot, so I moved the data out of the sheet schedule. 

Now a sample entry, Post Malone x Nirvana, is showing up under "Kids" despite being labeled in the data as "Music".

I was hoping to use it to test loading schedules to make sure they don't break the production app. Are we keeping it generally up to date with the production version?

**Comment by jjandoc** [comment]
Looks like my Github action wasn't automatically merging the code in from master. I've updated the code in demo branch and it seems to be loading fine now. I can revisit the automation, though if this fork is going to be serving as a demo and @exafox's is going to have the production deploy then maybe I don't need to worry about the demo branch at all?

**Comment by mstem** [comment]
Agreed - let's have the one demo paquete
