### ISSUE TITLE
Scrolling entries push actively playing Stitcher window

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#55]
See https://www.loom.com/share/be12d7678a414cb38dd4709fda2591ea for screencast

When you press play on the auto-focused podcast, it's interrupted when the next auto-focus selection appears

**Comment by jjandoc** [comment]
Pushed a fix for this though there are some limitations with what we can communicate between the page and the iframe'd content. We can detect if someone clicks in an iframe so when that happens I stop the shuffling of auto-focused selections. However I can't tell when the user is finished consuming the content (a video/podcast ends for example) so I don't have a cue to resume auto-shuffling. I think that's fine though, but wanted to flag that.

**Comment by mstem** [comment]
This fix works! Some of the content is pretty long so it's OK if we expect
the user to resume the autoscroll when they decide to.
