### ISSUE TITLE
Display (optional) link to press coverage

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#7]
If there the "Description Page Link (optional)" field is populated, append a paragraph break and then the text "Read about it in the Boston Globe." to the end of the listing's description. Link that text to the URL provided in the field.

**Comment by jjandoc** [comment]
So I already have this set up as a "Learn more" button

<img width="565" alt="Screen Shot 2020-05-09 at 12 51 05 PM" src="https://user-images.githubusercontent.com/801206/81483540-da134d80-91f3-11ea-9011-625d33ca963a.png">

How do we feel about that?

**Comment by mstem** [comment]
Works for now!
