### ISSUE TITLE
Update palette to use brand colors

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#71]
Update listings colors so that “Featured” (Globe) listings use #005DC7

Other cells should use colors from https://company-59374.frontify.com/d/ERwMkYdG4A1L/the-boston-globe#/visual-identity-guidelines/color-palette

**Comment by mstem** [comment]
Regular, non-featured listings can use #5DA9DD as a cell shading color

**Comment by mstem** [comment]
Please restyle to:

- Channel (leftmost column) cells background #000000
- Channel font #FFFFFF
- Default listing cell background #FFFFFF
- Default listing font #000000
- Action buttons (Play/pause, +, charity-hand) #9E1511

**Comment by margoyle** [comment]
Recommend:
- Channel (leftmost column) cells background #000000
- Channel font #FFFFFF
- Default listing cell background #444444
- Default listing font #FFFFFF
- Action buttons (Play/pause, +, charity-hand) #9E1511

**Comment by jjandoc** [comment]
updated

**Comment by mstem** [comment]
To incorporate @margoyle's updated palette (version F in the attached), can you please:
- fill default, non-selected listings with background color #444444
- restore the vertical accent bar in selected listings, and make it black (see the "LiveGuide" listing in version F of the attached)
[Uploading tv guide 0601.pdf…]()
