### ISSUE TITLE
"Loading" isn't visible to user on embedded page on mobile

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#79]
On mobile, can we vertical-top align the word loading so that it appears to the user while the app is loading?

**Comment by jjandoc** [comment]
We could do that, but I don't think I'd like how this would look on mobile with the liveguide as a standalone site. Can we see if they'd be open to resizing their iframe? Looks like at least on the Globe that the height is hard-coded to 1000px. If they do something like `90vh` then the iframe will be 90% of the screen height and the "Loading" text should be visible. This will also probably help with some of the UX issues.

**Comment by mstem** [comment]
Thanks - asking
