### ISSUE TITLE
On mobile, scrolling back up within the iframe goes on infinitely

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#80]
Could we set the app so that after scrolling up a certain number of rows, there's a stopping point, so that the user's up-scrolls revert to scrolling the container page instead of the iframe?

See 0:59 mark here: 
https://drive.google.com/file/d/1TH_MjqylvrYoPHZPSUbRPxgHi2v_m7sx/view?usp=sharing

**Comment by jjandoc** [comment]
Infinite scroll has been disabled on mobile screens. While a neat trick, if it's causing issues on small screens I think it's better to just ditch it.

**Comment by mstem** [comment]
Agree, thanks!
