### ISSUE TITLE
Action buttons aren't immediately visible to user in iframed version on mobile

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#81]
When it's embedded in https://www.bostonglobe.com/liveguide/, the action buttons aren't visible on mobile unless the user scrolls down significantly. Can we limit the height / number of grid rows when the app is displayed on smaller screens?

**Comment by jjandoc** [comment]
The guide is designed to fill its container so the best solution here would be for the Globe to reduce the height of their iframe. They would be in a better solution to make adjustments based on their site nav and any other existing elements on the page.
