### ISSUE TITLE
Help with livestream URLs

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#83]
I can't figure out what's going wrong with some of these Livestream URLs.

This URL loads a 404 in the media pane: https://livestream.com/accounts/12638529/watchmework/player?width=640&height=360

This URL loads a broken icon in the media pane: https://livestream.com/accounts/12638529/watchmework/

But the links resolve. Any ideas why the media pane can't use these URLs? Or how we might get Livestream links to at least display the placeholder image instead of a 404?
![broken](https://user-images.githubusercontent.com/613432/83689035-aa871380-a5ee-11ea-8f53-7a7d3b089597.png)
![livestream 404s](https://user-images.githubusercontent.com/613432/83689041-abb84080-a5ee-11ea-8461-d3b2421e51b7.png)

**Comment by jjandoc** [comment]
Okay, looks like the logic for turning a livestream link into an embed link is more complicated. I don't see a way to derive the embed link from the main link so we'll need to use the "embed" column in the spreadsheet for these. In the meantime, I'm swapping in the placeholder image.
