### ISSUE TITLE
Image dimensions are out of wack on Mac Firefox

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#84]
Compressed "LiveGuide" logo in Firefox on Mac
<img width="1439" alt="Screen Shot 2020-06-03 at 5 14 20 PM" src="https://user-images.githubusercontent.com/613432/83690406-f6d35300-a5f0-11ea-8a92-8a439cbf10bc.png">

**Comment by jjandoc** [comment]
Fix is up. This was a regression introduced by https://github.com/exafox/paquete/commit/bf99e63c17c15db21675b8a62866a7b11fa8d6dc which funny enough was a fix for the logo styling in Safari. Prior to that FF and Chrome were working fine. Apparently that fixed Safari and Chrome, but broke FF. https://github.com/exafox/paquete/commit/1f036bcd891678d6e762200cd3b0d098e9e9e807 fixes FF and I've tested in all three browsers to verify.
