### ISSUE TITLE
Is there anything we can do to speed up loading times?

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#86]
Paquete.netlify.app is loading very slowly (28-30 seconds in Firefox and Chrome). Is there anything we can do to optimize it, short of having fewer listing entries?

See example load here: https://drive.google.com/file/d/1TH_MjqylvrYoPHZPSUbRPxgHi2v_m7sx/view?usp=sharing

It triggered this warning in Firefox:
![slow](https://user-images.githubusercontent.com/613432/83765631-b66ce700-a67b-11ea-9b68-0cbeb2c2e2bf.png)

**Comment by jjandoc** [comment]
Made some tweaks so that there is less blocking code before the loading screen is turned off. I'm seeing better loading times now with the loading times coming in around 2 seconds now. Let me know if you're still seeing issues.
