### ISSUE TITLE
Safari desktop bugs

### ISSUE THREAD

**Issue by margoyle** [exafox/paquete#92]
"I just tried it and there are a couple bugs. The hours appear and disappear from the grid rather than being sticky at the top, and the watch button is truncated on some entries. There’s also some funky spacing going on with the type there as well - between hours and description."
Video in slack here: https://thegpf.slack.com/archives/G012X2MSDD0/p1591370613001900?thread_ts=1591196657.001900&cid=G012X2MSDD0

**Comment by jjandoc** [comment]
"Funky spacing" issue fixed by https://github.com/exafox/paquete/commit/ec8f0faab70ac0afac6cd0988575e60fc1ef1df3. Sticky header not always sticking is an open issue.

**Comment by jjandoc** [comment]
Sticky header issue is a weird one. Seems to be a bug in Safari, and seems to occur only when we have events that overlap on the timeline - though I would need to do more testing to confirm that. Also, of note the stickiness is also affected on sideways scrolling - sometimes the channel column disappears when you've scrolled a bit. Flagging that this may be a potentially time-consuming one to fix. First we should see if we can eliminate overlapping events from the time line and if that makes the issue go away.

**Comment by mstem** [comment]
Thanks for flagging that. I'll try to ensure there aren't any overlapping
schedule items (I have been trying but some slip through). If anyone knows
a good Sheets formula for conditionally formatting or otherwise flagging
overlapping schedule items, please let me know.

**Comment by jjandoc** [comment]
Okay, on further investigation it looks like the overlapping events issue is unrelated to the scrolling stickiness bug. This is a really tough one to fix, though. I've been banging my head on it for several hours now.

**Comment by mstem** [comment]
Thanks for trying to get it fixed. Safari desktop is ~15% of North American
desktop marketshare so we'll want to fix it or at least figure out a
fallback solution, if possible.

**Comment by jjandoc** [comment]
This has been fixed! Possibly the trickiest CSS bug I've had to tackle in years but we're good now.

**Comment by mstem** [comment]
HERO
